import {
  FiAward,
  FiBarChart2,
  FiBook,
  FiCheckCircle,
  FiClock,
  FiStar,
  FiTrendingUp,
  FiZap,
} from "react-icons/fi";

export const iconBubbles = [
  {
    Icon: FiStar,
    color: "text-violet-500",
    bg: "bg-violet-100",
    size: "w-5 h-5",
    box: "w-10 h-10",
    pos: "top-16 left-[10%]",
    delay: "0s",
    dur: "4s",
  },
  {
    Icon: FiZap,
    color: "text-indigo-500",
    bg: "bg-indigo-100",
    size: "w-5 h-5",
    box: "w-10 h-10",
    pos: "top-1/3 left-[6%]",
    delay: "0.8s",
    dur: "5s",
  },
  {
    Icon: FiAward,
    color: "text-fuchsia-500",
    bg: "bg-fuchsia-100",
    size: "w-5 h-5",
    box: "w-10 h-10",
    pos: "top-2/3 left-[12%]",
    delay: "1.4s",
    dur: "6s",
  },
  {
    Icon: FiBook,
    color: "text-sky-500",
    bg: "bg-sky-100",
    size: "w-5 h-5",
    box: "w-10 h-10",
    pos: "bottom-20 left-[8%]",
    delay: "0.4s",
    dur: "4.5s",
  },
  {
    Icon: FiTrendingUp,
    color: "text-emerald-500",
    bg: "bg-emerald-100",
    size: "w-5 h-5",
    box: "w-10 h-10",
    pos: "top-20 right-[10%]",
    delay: "0.6s",
    dur: "5.5s",
  },
  {
    Icon: FiCheckCircle,
    color: "text-violet-500",
    bg: "bg-violet-100",
    size: "w-5 h-5",
    box: "w-10 h-10",
    pos: "top-[40%] right-[7%]",
    delay: "1.2s",
    dur: "4s",
  },
  {
    Icon: FiClock,
    color: "text-pink-500",
    bg: "bg-pink-100",
    size: "w-5 h-5",
    box: "w-10 h-10",
    pos: "top-[65%] right-[12%]",
    delay: "0.2s",
    dur: "6.5s",
  },
  {
    Icon: FiBarChart2,
    color: "text-amber-500",
    bg: "bg-amber-100",
    size: "w-5 h-5",
    box: "w-10 h-10",
    pos: "bottom-16 right-[8%]",
    delay: "1s",
    dur: "5s",
  },
];

export const cardOrbit = [
  {
    Icon: FiZap,
    color: "text-violet-400",
    bg: "bg-violet-50",
    pos: "-top-5 -left-5",
    delay: "0s",
    dur: "3.5s",
  },
  {
    Icon: FiStar,
    color: "text-indigo-400",
    bg: "bg-indigo-50",
    pos: "-top-5 -right-5",
    delay: "0.7s",
    dur: "4s",
  },
  {
    Icon: FiAward,
    color: "text-fuchsia-400",
    bg: "bg-fuchsia-50",
    pos: "-bottom-5 -left-5",
    delay: "1.1s",
    dur: "4.5s",
  },
  {
    Icon: FiTrendingUp,
    color: "text-sky-400",
    bg: "bg-sky-50",
    pos: "-bottom-5 -right-5",
    delay: "0.4s",
    dur: "3.8s",
  },
];

export const registerSmallCircles = [
  {
    size: "w-4 h-4",
    pos: "top-[10%] left-[25%]",
    color: "bg-emerald-300/50",
    delay: "0s",
    dur: "4s",
  },
  {
    size: "w-2 h-2",
    pos: "top-[28%] left-[18%]",
    color: "bg-violet-400/40",
    delay: "1s",
    dur: "3.5s",
  },
  {
    size: "w-5 h-5",
    pos: "top-[50%] left-[20%]",
    color: "bg-sky-300/35",
    delay: "0.5s",
    dur: "5s",
  },
  {
    size: "w-3 h-3",
    pos: "top-[78%] left-[16%]",
    color: "bg-fuchsia-300/45",
    delay: "1.4s",
    dur: "6s",
  },
  {
    size: "w-2 h-2",
    pos: "top-[8%] right-[20%]",
    color: "bg-amber-300/50",
    delay: "0.3s",
    dur: "4.5s",
  },
  {
    size: "w-5 h-5",
    pos: "top-[40%] right-[22%]",
    color: "bg-indigo-300/35",
    delay: "0.8s",
    dur: "5.5s",
  },
  {
    size: "w-3 h-3",
    pos: "top-[68%] right-[17%]",
    color: "bg-rose-300/45",
    delay: "0.6s",
    dur: "3s",
  },
  {
    size: "w-4 h-4",
    pos: "top-[88%] right-[23%]",
    color: "bg-emerald-200/50",
    delay: "1.2s",
    dur: "7s",
  },
];

export const registerCardOrbit = [
  {
    Icon: FiBook,
    color: "text-emerald-400",
    bg: "bg-emerald-50",
    pos: "-top-5 -left-5",
    delay: "0.2s",
    dur: "4s",
  },
  {
    Icon: FiCheckCircle,
    color: "text-violet-400",
    bg: "bg-violet-50",
    pos: "-top-5 -right-5",
    delay: "0.9s",
    dur: "3.5s",
  },
  {
    Icon: FiZap,
    color: "text-amber-400",
    bg: "bg-amber-50",
    pos: "-bottom-5 -left-5",
    delay: "0.5s",
    dur: "4.5s",
  },
  {
    Icon: FiBarChart2,
    color: "text-sky-400",
    bg: "bg-sky-50",
    pos: "-bottom-5 -right-5",
    delay: "1.3s",
    dur: "3.8s",
  },
];

export const registerIconBubbles = [
  {
    Icon: FiBook,
    color: "text-emerald-500",
    bg: "bg-emerald-100",
    size: "w-5 h-5",
    box: "w-10 h-10",
    pos: "top-10 left-[14%]",
    delay: "0.3s",
    dur: "5s",
  },
  {
    Icon: FiCheckCircle,
    color: "text-violet-500",
    bg: "bg-violet-100",
    size: "w-5 h-5",
    box: "w-10 h-10",
    pos: "top-[38%] left-[8%]",
    delay: "1.1s",
    dur: "4s",
  },
  {
    Icon: FiBarChart2,
    color: "text-sky-500",
    bg: "bg-sky-100",
    size: "w-5 h-5",
    box: "w-10 h-10",
    pos: "top-[65%] left-[5%]",
    delay: "0.5s",
    dur: "6s",
  },
  {
    Icon: FiClock,
    color: "text-pink-500",
    bg: "bg-pink-100",
    size: "w-5 h-5",
    box: "w-10 h-10",
    pos: "bottom-14 left-[13%]",
    delay: "1.5s",
    dur: "4.5s",
  },
  {
    Icon: FiZap,
    color: "text-amber-500",
    bg: "bg-amber-100",
    size: "w-5 h-5",
    box: "w-10 h-10",
    pos: "top-12 right-[14%]",
    delay: "0.7s",
    dur: "5.5s",
  },
  {
    Icon: FiTrendingUp,
    color: "text-indigo-500",
    bg: "bg-indigo-100",
    size: "w-5 h-5",
    box: "w-10 h-10",
    pos: "top-[35%] right-[6%]",
    delay: "0s",
    dur: "4s",
  },
  {
    Icon: FiAward,
    color: "text-fuchsia-500",
    bg: "bg-fuchsia-100",
    size: "w-5 h-5",
    box: "w-10 h-10",
    pos: "top-[62%] right-[9%]",
    delay: "1.3s",
    dur: "6.5s",
  },
  {
    Icon: FiStar,
    color: "text-rose-500",
    bg: "bg-rose-100",
    size: "w-5 h-5",
    box: "w-10 h-10",
    pos: "bottom-12 right-[14%]",
    delay: "0.6s",
    dur: "5s",
  },
];
